import React from 'react'

export default function About() {
  return (
    <div className='m-10'>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, tenetur? Ad reiciendis ullam magnam sit, soluta esse ea similique temporibus aliquam. Assumenda corrupti repellat explicabo aliquid voluptates blanditiis tempora, neque rem. Minima odit dignissimos dolor exercitationem, quisquam ipsam blanditiis, dolores, molestias totam vero hic odio magnam esse cumque ea recusandae laudantium ab facilis expedita! Iste, ad praesentium. Ut nisi veritatis omnis! Eos quas corrupti adipisci! Nulla eum architecto cumque. Unde, quasi atque ipsum porro eligendi, aut eaque officia veritatis pariatur dolorum vel recusandae? Eos ipsa eum, iusto eveniet inventore exercitationem sunt labore sed sit iste ullam possimus porro reprehenderit enim alias corporis vel vero nulla accusamus facilis velit, quidem ad molestiae. Sapiente iusto cupiditate ut, totam eum nemo dignissimos voluptatem ab deleniti dolorem eveniet? Magni corporis hic porro libero modi voluptate corrupti? Assumenda, accusantium alias a magnam ea repellat ullam fugit modi? Aliquid non natus, aperiam quam aliquam totam quidem qui sequi amet fugit, rerum voluptatum animi ad sint nisi reiciendis soluta iste numquam quis vitae? Id, illo? Veritatis esse natus nisi libero asperiores nostrum ducimus eius mollitia. Quia nisi ut, sit, dolore dicta ex deserunt quae nesciunt rerum fugiat asperiores. Eligendi, voluptates? Ratione facilis sit, beatae quis hic, eaque nesciunt esse iusto vero assumenda quidem perspiciatis sint inventore! Quia inventore similique quam expedita molestias, culpa sit iusto minus, ad ducimus dignissimos numquam alias dicta hic. Eum provident quas velit nihil vero fuga tempora modi autem in quisquam ratione itaque, doloremque dignissimos hic delectus est veniam dicta perspiciatis corrupti repellendus explicabo! Provident dicta magni aliquid. Rerum commodi quos repellendus minima voluptatibus! Maiores culpa accusamus nemo fugiat modi, voluptatibus voluptates repudiandae perspiciatis laudantium, molestias aliquid possimus consectetur asperiores illum quia nihil nostrum nobis magnam numquam libero velit similique, optio iusto autem! Ut veritatis nobis iure voluptatibus. Neque blanditiis esse assumenda maiores?</p>
    </div>
  )
}
